const STORAGE_KEY = 'studyboard_v1';
const initialState = { courses: [{ id: 'course-1', name: 'Cognitive Psychology', code: 'PSYC 301' }, { id: 'course-2', name: 'Modern Literature', code: 'LIT 214' }, { id: 'course-3', name: 'Data & Society', code: 'SOC 220' }], assignments: [{ id: 'assignment-1', title: 'Memory & Attention essay', courseId: 'course-1', dueDate: '2026-09-08', priority: 'high', status: 'progress' }, { id: 'assignment-2', title: 'Reading response 03', courseId: 'course-2', dueDate: '2026-09-10', priority: 'medium', status: 'todo' }, { id: 'assignment-3', title: 'Methods worksheet', courseId: 'course-3', dueDate: '2026-09-12', priority: 'low', status: 'todo' }, { id: 'assignment-4', title: 'Field notes synthesis', courseId: 'course-3', dueDate: '2026-09-04', priority: 'medium', status: 'done' }] };
let state = loadState();
let editingCourseId = null;
let editingAssignmentId = null;
const $ = (selector) => document.querySelector(selector);
function loadState() { try { const saved = JSON.parse(localStorage.getItem(STORAGE_KEY)); return saved?.courses && saved?.assignments ? saved : structuredClone(initialState); } catch { return structuredClone(initialState); } }
function saveState() { localStorage.setItem(STORAGE_KEY, JSON.stringify(state)); }
function dateLabel(value, options = { month: 'short', day: 'numeric' }) { return new Date(`${value}T12:00:00`).toLocaleDateString('en-US', options); }
function daysUntil(value) { return Math.ceil((new Date(`${value}T12:00:00`) - new Date('2026-09-04T12:00:00')) / 86400000); }
function courseName(id) { return state.courses.find((course) => course.id === id)?.name || 'Unassigned course'; }
function renderStats() { const total = state.assignments.length; const done = state.assignments.filter((item) => item.status === 'done').length; const due = state.assignments.filter((item) => item.status !== 'done' && daysUntil(item.dueDate) >= 0 && daysUntil(item.dueDate) <= 7).length; $('#due-count').textContent = due; $('#progress-count').textContent = state.assignments.filter((item) => item.status === 'progress').length; $('#course-count').textContent = state.courses.length; $('#completed-count').textContent = done; $('#assignment-count').textContent = total; const percent = total ? Math.round(done / total * 100) : 0; $('#progress-value').textContent = `${percent}%`; $('#progress-bar').style.width = `${percent}%`; }
function renderCourses() { $('#course-empty').hidden = state.courses.length > 0; $('#course-list').innerHTML = state.courses.map((course) => `<div class="course-item"><div class="course-info"><strong>${course.name}</strong><span>${course.code} / ${state.assignments.filter((item) => item.courseId === course.id).length} assignments</span></div><div class="course-actions"><button class="edit-course" data-id="${course.id}" type="button">Edit</button><button class="delete-course" data-id="${course.id}" type="button" aria-label="Delete ${course.name}">x</button></div></div>`).join(''); document.querySelectorAll('.edit-course').forEach((button) => button.addEventListener('click', () => openCourseDialog(button.dataset.id))); document.querySelectorAll('.delete-course').forEach((button) => button.addEventListener('click', () => deleteCourse(button.dataset.id))); }
function renderUpcoming() { const items = [...state.assignments].filter((item) => item.status !== 'done').sort((a, b) => a.dueDate.localeCompare(b.dueDate)).slice(0, 3); $('#upcoming-empty').hidden = items.length > 0; $('#upcoming-list').innerHTML = items.map((item) => { const date = new Date(`${item.dueDate}T12:00:00`); return `<div class="upcoming-item"><div class="date-block"><strong>${date.getDate()}</strong>${date.toLocaleDateString('en-US', { month: 'short' })}</div><div><strong>${item.title}</strong><span>${courseName(item.courseId)}</span></div><time>${daysUntil(item.dueDate) === 0 ? 'Today' : `In ${daysUntil(item.dueDate)} days`}</time></div>`; }).join(''); }
function renderFilters() { const selected = $('#course-filter').value; $('#course-filter').innerHTML = '<option value="all">All courses</option>' + state.courses.map((course) => `<option value="${course.id}">${course.code}</option>`).join(''); $('#course-filter').value = state.courses.some((course) => course.id === selected) ? selected : 'all'; $('#assignment-course').innerHTML = state.courses.map((course) => `<option value="${course.id}">${course.code} - ${course.name}</option>`).join(''); }
function renderAssignments() { const query = $('#search-input').value.toLowerCase().trim(); const course = $('#course-filter').value; const status = $('#status-filter').value; const items = state.assignments.filter((item) => (!query || item.title.toLowerCase().includes(query) || courseName(item.courseId).toLowerCase().includes(query)) && (course === 'all' || item.courseId === course) && (status === 'all' || item.status === status)).sort((a, b) => a.dueDate.localeCompare(b.dueDate)); $('#assignment-empty').hidden = items.length > 0; $('#assignment-list').innerHTML = items.map((item) => `<tr><td>${item.title}</td><td>${courseName(item.courseId)}</td><td>${dateLabel(item.dueDate, { month: 'short', day: 'numeric', year: 'numeric' })}</td><td><select class="priority ${item.priority}" data-id="${item.id}" aria-label="Change priority for ${item.title}"><option value="low" ${item.priority === 'low' ? 'selected' : ''}>Low</option><option value="medium" ${item.priority === 'medium' ? 'selected' : ''}>Medium</option><option value="high" ${item.priority === 'high' ? 'selected' : ''}>High</option></select></td><td><select class="status ${item.status}" data-id="${item.id}" aria-label="Change status for ${item.title}"><option value="todo" ${item.status === 'todo' ? 'selected' : ''}>To do</option><option value="progress" ${item.status === 'progress' ? 'selected' : ''}>In progress</option><option value="done" ${item.status === 'done' ? 'selected' : ''}>Complete</option></select></td><td class="row-actions"><button class="row-action edit-assignment" data-id="${item.id}" type="button">Edit</button><button class="row-action delete-action delete-assignment" data-id="${item.id}" type="button" aria-label="Delete ${item.title}">x</button></td></tr>`).join(''); document.querySelectorAll('.edit-assignment').forEach((button) => button.addEventListener('click', () => openAssignmentDialog(button.dataset.id))); document.querySelectorAll('.delete-assignment').forEach((button) => button.addEventListener('click', () => deleteAssignment(button.dataset.id))); document.querySelectorAll('.priority').forEach((select) => select.addEventListener('change', (event) => updateAssignment(event.target.dataset.id, { priority: event.target.value }))); document.querySelectorAll('.status').forEach((select) => select.addEventListener('change', (event) => updateAssignment(event.target.dataset.id, { status: event.target.value }))); }
function render() { renderStats(); renderCourses(); renderUpcoming(); renderFilters(); renderAssignments(); }
function deleteCourse(id) { if (!confirm('Delete this course and its assignments?')) return; state.courses = state.courses.filter((course) => course.id !== id); state.assignments = state.assignments.filter((item) => item.courseId !== id); saveState(); render(); }
function deleteAssignment(id) { state.assignments = state.assignments.filter((item) => item.id !== id); saveState(); render(); }
function updateAssignment(id, changes) { state.assignments = state.assignments.map((item) => item.id === id ? { ...item, ...changes } : item); saveState(); render(); }
function openCourseDialog(id = null) { editingCourseId = id; const course = state.courses.find((item) => item.id === id); $('#course-dialog-title').textContent = id ? 'Edit course' : 'Add course'; $('#course-form').reset(); if (course) { $('#course-form [name="name"]').value = course.name; $('#course-form [name="code"]').value = course.code; } $('#course-dialog').showModal(); }
function openAssignmentDialog(id = null) { editingAssignmentId = id; const assignment = state.assignments.find((item) => item.id === id); $('#assignment-dialog-title').textContent = id ? 'Edit assignment' : 'Add assignment'; renderFilters(); $('#assignment-form').reset(); if (assignment) Object.entries(assignment).forEach(([key, value]) => { const field = $(`#assignment-form [name="${key}"]`); if (field) field.value = value; }); else if (state.courses[0]) $('#assignment-course').value = state.courses[0].id; $('#assignment-dialog').showModal(); }
$('#course-form').addEventListener('submit', (event) => { event.preventDefault(); const data = new FormData(event.currentTarget); const course = { name: data.get('name').trim(), code: data.get('code').trim() }; if (editingCourseId) state.courses = state.courses.map((item) => item.id === editingCourseId ? { ...item, ...course } : item); else state.courses.push({ id: `course-${Date.now()}`, ...course }); saveState(); $('#course-dialog').close(); render(); });
$('#assignment-form').addEventListener('submit', (event) => { event.preventDefault(); const data = new FormData(event.currentTarget); const assignment = { title: data.get('title').trim(), courseId: data.get('courseId'), dueDate: data.get('dueDate'), priority: data.get('priority'), status: data.get('status') }; if (editingAssignmentId) state.assignments = state.assignments.map((item) => item.id === editingAssignmentId ? { ...item, ...assignment } : item); else state.assignments.push({ id: `assignment-${Date.now()}`, ...assignment }); saveState(); $('#assignment-dialog').close(); render(); });
$('#add-course-button').addEventListener('click', () => openCourseDialog()); $('#add-assignment-button').addEventListener('click', () => openAssignmentDialog()); $('#search-input').addEventListener('input', renderAssignments); $('#course-filter').addEventListener('change', renderAssignments); $('#status-filter').addEventListener('change', renderAssignments); $('#focus-button').addEventListener('click', () => { $('#status-filter').value = 'all'; $('#course-filter').value = 'all'; $('#search-input').value = ''; renderAssignments(); $('#assignments-panel').scrollIntoView({ behavior: 'smooth' }); }); $('#today-label').textContent = new Date('2026-09-04T12:00:00').toLocaleDateString('en-US', { weekday: 'long', month: 'long', day: '2-digit', year: 'numeric' }); render();
